version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    container_name: shopfusion-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - shopfusion-network

  backend:
    build:
      context: ./backend
    container_name: shopfusion-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb+srv://ram:Pass1234@cluster0.2ycwei8.mongodb.net/shopfusion
      JWT_SECRET: your_jwt_secret_key_here_make_it_strong
      JWT_EXPIRE: 30d
      MIN_SUPPORT: 0.01
      MIN_CONFIDENCE: 0.3
      MIN_LIFT: 1.0
      PYTHON_API_URL: http://ml-engine:8000
      USE_PYTHON_ENGINE: "false"
      CLIENT_URL: http://localhost:3000
    depends_on:
      - ml-engine
    networks:
      - shopfusion-network

  ml-engine:
    build:
      context: ./ml-engine
    container_name: shopfusion-ml
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb+srv://ram:Pass1234@cluster0.2ycwei8.mongodb.net/shopfusion
      DB_NAME: shopfusion
      PORT: 8000
    networks:
      - shopfusion-network

networks:
  shopfusion-network:
    driver: bridge