apiVersion: apps/v1
kind: Deployment

metadata:
  name: ml-engine
  namespace: shopfusion
  labels:
    app: ml-engine

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ml-engine

  template:
    metadata:
      labels:
        app: ml-engine

    spec:
      containers:
        - name: ml-engine
          image: rameshwarrm/shopfusion-ml-engine:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
          - configMapRef:
            name: ml-config

          - secretRef:
            name: ml-secret